// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission6.Models;

namespace Mission6.Migrations
{
    [DbContext(typeof(MovieContext))]
    [Migration("20230326042432_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Mission6.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Action"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "Adventure"
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "Comedy"
                        },
                        new
                        {
                            CategoryID = 4,
                            CategoryName = "Drama"
                        },
                        new
                        {
                            CategoryID = 5,
                            CategoryName = "Fantasy"
                        },
                        new
                        {
                            CategoryID = 6,
                            CategoryName = "Horror"
                        },
                        new
                        {
                            CategoryID = 7,
                            CategoryName = "Musical"
                        },
                        new
                        {
                            CategoryID = 8,
                            CategoryName = "Mystery"
                        },
                        new
                        {
                            CategoryID = 9,
                            CategoryName = "Romance"
                        },
                        new
                        {
                            CategoryID = 10,
                            CategoryName = "Science Fiction"
                        },
                        new
                        {
                            CategoryID = 11,
                            CategoryName = "Sports"
                        },
                        new
                        {
                            CategoryID = 12,
                            CategoryName = "Thriller"
                        },
                        new
                        {
                            CategoryID = 13,
                            CategoryName = "Western"
                        });
                });

            modelBuilder.Entity("Mission6.Models.MovieResponse", b =>
                {
                    b.Property<int>("MovieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieID");

                    b.HasIndex("CategoryID");

                    b.ToTable("responses");

                    b.HasData(
                        new
                        {
                            MovieID = 1,
                            CategoryID = 1,
                            Director = "Steven Caple Jr.",
                            Edited = false,
                            Rating = "PG-13",
                            Title = "Creed II",
                            Year = 2018
                        },
                        new
                        {
                            MovieID = 2,
                            CategoryID = 4,
                            Director = "Gus Van Sant",
                            Edited = false,
                            Rating = "R",
                            Title = "Good Will Hunting",
                            Year = 1997
                        },
                        new
                        {
                            MovieID = 3,
                            CategoryID = 1,
                            Director = "James Mangold",
                            Edited = false,
                            Rating = "PG-13",
                            Title = "Ford v Ferrari",
                            Year = 2019
                        });
                });

            modelBuilder.Entity("Mission6.Models.MovieResponse", b =>
                {
                    b.HasOne("Mission6.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
