// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission6.Models;

namespace Mission6.Migrations
{
    [DbContext(typeof(MovieContext))]
    [Migration("20230322192730_Mission6")]
    partial class Mission6
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Mission6.Models.MovieResponse", b =>
                {
                    b.Property<int>("MovieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieID");

                    b.ToTable("responses");

                    b.HasData(
                        new
                        {
                            MovieID = 1,
                            Category = "Action/Sport",
                            Director = "Steven Caple Jr.",
                            Edited = false,
                            Rating = "PG-13",
                            Title = "Creed II",
                            Year = 2018
                        },
                        new
                        {
                            MovieID = 2,
                            Category = "Drama",
                            Director = "Gus Van Sant",
                            Edited = false,
                            Rating = "R",
                            Title = "Good Will Hunting",
                            Year = 1997
                        },
                        new
                        {
                            MovieID = 3,
                            Category = "Action",
                            Director = "James Mangold",
                            Edited = false,
                            Rating = "PG-13",
                            Title = "Ford v Ferrari",
                            Year = 2019
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
